package com.example.demo.dao;

import com.example.demo.dataObject.ShopDO;
import com.example.demo.dataObject.ShopDOExample;

public interface ShopDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    long countByExample(ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    int insert(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    int insertSelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    ShopDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    int updateByPrimaryKeySelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Fri Nov 22 21:11:07 CST 2019
     */
    int updateByPrimaryKey(ShopDO record);
}